### ISSUE TITLE
healpy plots

### ISSUE THREAD

**Issue by jegarfa** [DhayaaAnbajagane/Ulagam-simulations#1]
I am trying to reproduce one of your HEALPix maps using the Ulagam density fields. However, my initial attempt at plotting resulted in very uniform maps, while I was expecting to see cosmic structures. I suspect I might be doing something wrong, but I haven't been able to pinpoint the issue. Here’s what I’ve done so far. Could you please provide some guidance on how to correctly plot the density field as you did?
Thank you!

```
counts  = fits.open("Density_shell.00100.fits.fz")[1].data
overdensity = counts/np.mean(counts) - 1
print(np.min(overdensity), np.max(overdensity))

hp.mollview(overdensity, title="HEALPix Map", norm='hist', cmap='viridis', cbar=True, min=-1, max=50)
plt.show()
```

![image](https://github.com/user-attachments/assets/3b9ac3fb-29f5-4428-9140-f4fd17c01eca)

**Comment by DhayaaAnbajagane** [comment]
Thanks for your interest in the simulations. Based on the code above, you are actually doing all the plotting/calculations correctly! Couple of notes:

1. There are 100 snapshots/shells, and 100 corresponds to z = 0. So for shell 100, the lightcone is not really well-sampled, and it will appear very patchy. If you plot slightly higher redshift shells (like even 90 or 80) the filamentary structure will show up more easily.
2. The density field at a given redshift is highly asymmetric, and it is better to plot log10(1 + overdensity) rather than linear density. If you do the latter, then the dynamic range of the colorbar is too large and so you end up seeing only the peaks in the distribution and then all the underdense space.

I suggest you try these two things and then follow-up if you are still unable to see cosmic structures.

**Comment by jegarfa** [comment]
Thanks, it worked indeed! I had to adjust a smoothing parameter, but I am getting the cosmic structure.
I am closing the question. Thanks!

![image](https://github.com/user-attachments/assets/19f9a646-8f7f-4fb9-a55e-92ced752737a)
